### 业务单上传成功
POST https://api-i.test.xforceplus.com/bizorder/jiayiDemo/default/v1/bizorders/action/flat-upload
Content-Type: application/json
Accept-Encoding: deflate
Authentication: standard-open-platform-demoTN1618456256032
uiaSign: badd0f229c223681562a2f3f65cb0824
serialNo: a1234567890

{
  "source": "financial",
  "accountType": "AR",
  "bizOrderUploadData": [
    {
      "bizOrderNo": "SOPD-000002",
      "customerBizOrderCategory": "默认业务单",
      "invoiceType": "s",
      "pricingMethod": "0",
      "sellerName": "上海甲公司",
      "sellerTaxNo": "99999999999999999U",
      "sellerTel": "021-88888888",
      "sellerAddress": "上海市沪太路2999弄",
      "sellerBankName": "中国建设银行",
      "sellerBankAccount": "6666666666666666",
      "buyerName": "武汉市丰业电器有限公司",
      "buyerTaxNo": "91420111271850146W",
      "buyerTel": "15771092589",
      "buyerAddress": "上海宝山",
      "buyerBankName": "上海农业银行",
      "buyerBankAccount": "622110046350777",
      "amountWithTax": "10900.00",
      "amountWithoutTax": "10000.00",
      "taxAmount": "900.00",
      "outterDiscountWithTax": "0.0",
      "outterDiscountWithoutTax": "0.0",
      "innerDiscountWithTax": "0.0",
      "innerDiscountWithoutTax": "0.0",
      "outterPrepayAmountWithTax": "0.0",
      "outterPrepayAmountWithoutTax": "0.0",
      "innerPrepayAmountWithTax": "0.0",
      "innerPrepayAmountWithoutTax": "0.0",
      "reviewer": "张三",
      "payee": "李四",
      "issuer": "王五",
      "originInvoiceNo": "",
      "originInvoiceCode": "",
      "originDateIssued": "",
      "originInvoiceType": "",
      "redLetterNumber": "",
      "businessAttrs": {
        "receiverEmail": "jia1@xforceplus.com",
        "receiverTel": "",
        "remark": "测试备注"
      },
      "extendedAttrs": {
        "ext1": "",
        "ext2": "",
        "ext3": "",
        "ext4": "",
        "ext5": "",
        "ext6": ""
      },
      "details": [
        {
          "bizOrderDetailNo": "J-ITEM-0001",
          "detailCategory": "",
          "remark": "明细备注",
          "goodsTaxNo": "1090137020000000000",
          "taxConvertCode": "",
          "taxPre": "0",
          "taxPreCon": "0",
          "zeroTax": "",
          "itemCode": "水泥",
          "itemName": "水泥",
          "specifications": "水泥",
          "unit": "袋",
          "quantity": "1.0",
          "unitPrice": "10000.00",
          "amountWithTax": "10900.00",
          "amountWithoutTax": "10000.00",
          "taxAmount": "900.00",
          "taxRate": "0.09",
          "deduction": "0.0",
          "outterDiscountWithTax": "0.0",
          "outterDiscountWithoutTax": "0.0",
          "outterDiscountTax": "0.0",
          "innerDiscountWithTax": "0.0",
          "innerDiscountWithoutTax": "0.0",
          "innerDiscountTax": "0.0",
          "outterPrepayAmountWithoutTax": "0.0",
          "outterPrepayAmountTax": "0.0",
          "outterPrepayAmountWithTax": "0.0",
          "innerPrepayAmountWithTax": "0.0",
          "innerPrepayAmountWithoutTax": "0.0",
          "innerPrepayAmountTax": "0.0",
          "detailExtendedAttrs": {
            "ext1": "",
            "ext2": "",
            "ext3": "",
            "ext4": "",
            "ext5": "",
            "ext6": ""
          }
        }
      ]
    }
  ]
}


###
POST https://api-i.test.xforceplus.com/bizorder/TKE/default/v1/bizorders/action/flat-upload
Content-Type: application/json
Accept-Encoding: deflate
Authentication: standard-open-platform-demoTN1618456256032
uiaSign: 8f8c5f09a85066b92ea8bec2b241cbc4
serialNo: com.xforceplus.ultraman.demo.utils.UUID@3f8ac843

{
  "accountType": "AR",
  "bizOrderUploadData": [
    {
      "amountWithTax": "10.0",
      "bizOrderNo": "BO202204141920470001",
      "buyerNo": "TS",
      "customerBizOrderCategory": "开票通知单",
      "details": [
        {
          "amountWithoutTax": "10.0",
          "bizOrderDetailNo": "1514549165030375424",
          "deduction": "0",
          "detailCategory": "",
          "itemCode": "111111-111",
          "quantity": "2.0"
        },
        {
          "amountWithoutTax": "10.0",
          "bizOrderDetailNo": "1514551608443142144",
          "deduction": "0",
          "detailCategory": "",
          "itemCode": "111111-111",
          "quantity": "2.0"
        }
      ],
      "invoiceType": "ce",
      "pricingMethod": "1",
      "sellerName": "上海普宏建设工程有限公司",
      "sellerNo": "3001151839"
    }
  ]
}
